### PR TITLE
fixing issue #1

### PR DESCRIPTION
**Pull request by Zbysekz**
As described in #1

### CODE REVIEW

**Comment by feyzikesim** [comment]
Hi, thanks for your contribution. You are right about the reserved bits, I missed it. I'll try the changes in the coming days and let you know. But I have a question. Just checked your commit, and I think [this](https://github.com/feyzikesim/sht20/pull/2/commits/d41c184f9d5d6e1235b7e1692269f4e176f95421#diff-aa062e129070c932631e741b61c4a11b3b40c9d51b5dd0df76fa9cb5b2ced881R66) line should be;

`userReg =  self.bus.read_byte_data(self.SHT20_ADDR, self.READ_USER_REG)` 

According to the **Table 6** of the datasheet. 'Read User Register' byte should be **0xE7** and its already defined as **READ_USER_REG** in the SHT20 class. If you are able to try before me, can you give it a shot.

**Comment by Zbysekz** [comment]
Ups, you are right, it was typo.
I have now tested this and it works too.. (not sure why it wasn't making any difference).

**Comment by sergiomfsilva** [comment]
Hi, 

After check those corrections they are not published in a new version and not merged. Can you please put this new corrections in a new version?

Best Regards

**Comment by feyzikesim** [comment]
Hey guys, sorry for late response. I was not able to try the fixes, my sensor is at the office and I am working from home for a long time. Actually I still have not tried but merged the request and deployed package to the PyPi. If there is something wrong with the new version (packaging may be a problem), please let me know. Thanks again for the contribution @Zbysekz. Best regards

**Pull request merged**
